services:
  tps:
    build: .
    environment:
      GIN_MODE: "release"
      BIND_ADDR: ":8080"
      DB_PATH: "/var/local/tps/data/tps.db"
    volumes:
      - custom-templates:/var/local/tps/templates
      - tps-data:/var/local/tps/data

volumes:
  custom-templates: {}
  tps-data: {}
